project_id = "dtpcijveikvuxuinekjh"

[functions.create-checkout]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.claim-daily-reward]
verify_jwt = false

[functions.spin-wheel]
verify_jwt = false

[functions.spend-coins]
verify_jwt = false
